version: '3.9'

services:
  api:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./src:/app/src
      - ./wsgi.py:/app/wsgi.py
    environment:
      - FLASK_ENV=production
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
