services:
  api:
    build:
      context: ./backend/
    container_name: calculator_api
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend/
    container_name: calculator_front
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "5173:5173"